### ISSUE TITLE
Error: Cannot find module 'chalk'

### ISSUE THREAD

**Issue by NetOpWibby** [composi/create-composi-app#1]
I installed this module globally and then tried to create a composi app.

```bash
Error: Cannot find module 'chalk'
    at Object.<anonymous> (~/.nvm/versions/node/v11.0.0/lib/node_modules/create-composi-app/index.js:8:15)
```

**Comment by rbiggs** [comment]
Yup, moved chalk into dependencies. Update to version 0.7.3 and you'll be fine.

**Comment by rbiggs** [comment]
I kept thinking your handle reminds me of a song, but I couldn't remember which one. Then it just hit me: Smooth Operator by Sade. he he.
